general:
  prefix: '&a&lClassroom &8> &r'
error:
  no-permission: '&cYou don''t have the permission to do that!'
  not-in-room: '&cJoin a lesson first before doing that!'
  already-in-room: '&cThis player is already following/teaching a lesson!'
  only-players: '&cOnly players can do that!'
  not-teaching: '&cYou''re not teaching currently!'
  no-lessons-available: '&cThere aren''t any lessons available at the moment!'
  talking-not-allowed: '&cTalking is not allowed at the moment!'
  raising-hand-not-allowed: '&cRaising your hand is not allowed at the moment!'
  room-already-exists: '&cThis room already exists!'
  already-raised-hand: '&cYou already raised your hand once!'
  chair-occupied: '&cSomeone is already sitting on this chair.'
  command-not-allowed: '&cThis command isn''t allowed while in class!'
  item-not-allowed: '&cThis item can''t be given to your students!'
  magic-not-allowed: '&cYou can''t cast any spell at the moment.'
  spell-not-allowed: '&cThis spell is never allowed in class!'
  wrong-command-usage: '&cYou used the command wrong. Do &4/class help &cfor a complete
    list!'
  invalid-argument: '&cThe argument you used (player or soemthing else) is invalid.'
  hand-in-must-be-book: '&cThe item you wanted to hand in is not a book!'
  hand-in-not-allowed: '&cThe item you wanted to hand in is not allowed!'
  wait-before-handing-in: '&cYou can''t hand in your essay right now!'
  already-handed-in: '&cYou already handed in your essay!'
  no-free-space: '&cYour inventory is already full!'
  too-many-classes: '&cYour server can only run 28 classes at the same time!'
  not-an-integer: '&cPlease specify an integer higher or equal to 0 and lower or equal
    to the max grade!'
trigger:
  announce-class: '&7There is a new lesson available: &a[name]&7!'
  new-teacher: '&7Your new teacher of this class is &a[name]&7!'
  not-teacher-anymore: '&7You''re class has been taken over, you''re not the teacher
    anymore!'
  item-has-been-given: '&7You got an item from the teacher.'
  started-lesson: '&7The lesson has started! Be quiet please!'
  ended-lesson: '&7The lesson has ended. Have a relaxing weekend!'
  joined-room: '&a[name] &7is now attending the lesson!'
  teacher-left: '&7The teacher left the room, that''s why you were kicked out if it.'
  talking-allowed: '&7You can now talk with the teacher and your fellow classmates.'
  talking-not-allowed: '&7Silence please! The teacher is going to explain something.'
  raising-hand-allowed: '&7You can now raise your hand to answer this question (&a/rh&7)'
  raising-hand-not-allowed: '&7You can''t raise your hand right now.'
  magic-allowed: '&7You can cast spells in this lesson, but ask your teacher if it''s
    your turn.'
  magic-not-allowed: '&7Please hold your wands from now on.'
  player-raised-hand: '&a[name] &7raised his/her hand.'
  player-can-speak: '&a[name]&7, please answer the question.'
  player-has-been-kicked: '&a[name] &7has been kicked out of the lesson!'
  graded: '&7You have been graded &a[grade]&7/&a[max]&7!'
  handed-in: '&a[name] &7handed in their essay.'
  received-money: '&7You earned &a[money] &7from this class. Current balance: &a[balance]&7.'
task:
  give-name: '&7Please send the name of your arena in the chat.'
  rightclick-item: '&7Please rightclick with the item you want to give.'
  give-grade: '&7Please send the grade of this player in the chat (max: &a[max]&7).'
success:
  set-main-spawn: '&7Set the main spawn to your location.'
  set-new-spawn: '&7Set the new spawn to your location.'
  gave-item: '&7The item has been given to all players.'
  graded-player: '&7Graded the player!'
  joined-room: '&7You succesfully joined the lesson &a[name]&7!'
  left-room: '&7You left your lesson.'
  teleported-to-room: '&7Teleported you to the room.'
  removed-room: '&7Removed the room.'
  created-room: '&7Created a room.'
  started-room: '&7Started the class! You''re the teacher'
  took-over-room: '&7You took over this lesson.'
  started-lesson: '&7You began with teaching this lesson!'
  ended-lesson: '&7You ended this lesson!'
  handed-in: '&7You handed in your essay!'
  reloaded: '&7Reloaded the plugin (&a[time]&7ms)'
list:
  help:
    player:
    - ' '
    - '&8> &a&lHelp page'
    - '&a&l/class leave &8/ &7Leave your current lesson.'
    - '&a&l/class stats &8/ &7View your statistics.'
    - '&a&l/lessons &8/ &7Open all available lessons.'
    - '&a&l/raisehand &7 or &a&l/rh &8/ &7Raise your hand.'
    - '&a&l/handin &8/ &7Hand in your essay.'
    - ' '
    teacher:
    - ' '
    - '&8> &a&lHelp page'
    - '&a&l/class help &8/ &7Open this help page.'
    - '&a&l/class reload &8/ &7Reload the config files. &c(Admin)'
    - '&a&l/class leave &8/ &7Leave your current lesson.'
    - '&a&l/class stats <player> &8/ &7View your statistics. &c(Admin: player argument)'
    - '&a&l/class forcejoin <player> &8/ &7Let a player join your class, even after
      it started.'
    - '&a&l/rooms &8/ &7Open the room overview menu.'
    - '&a&l/lessons &8/ &7Open all available lessons.'
    - '&a&l/raisehand &7 or &a&l/rh &8/ &7Raise your hand.'
    - '&a&l/handin &8/ &7Hand in your essay'
    - ' '
  stats:
  - ' '
  - '&8> &a&lStats of [player]'
  - '&8- &aClasses attended: &7[classesattended]'
  - '&8- &aAverage score: &7[average]%'
  - ' '
